theme: jekyll-theme-minimal
title: Harrison Nicholls
description: Portfolio
baseurl: ""
url: ""
github_username: hnicholls
linkedin_username: harrison-nicholls
show_downloads: false
logo: /assets/img/profile.jpg

# Social/contact links for sidebar
author:
  name: Harrison Nicholls
  email: nichollsharrisonj@gmail.com
  linkedin: nichollsharrisonj
